### ISSUE TITLE
create_tf_record.py

### ISSUE THREAD

**Issue by Powerfulboy** [PanJinquan/tensorflow_models_nets#16]
Traceback (most recent call last):
  File "/home/z/tensorflow_models_learning-master/create_tf_record.py", line 303, in <module>
    train_nums=get_example_nums(train_record_output)
  File "/home/z/tensorflow_models_learning-master/create_tf_record.py", line 39, in get_example_nums
    for record in tf.python_io.tf_record_iterator(tf_records_filenames):
  File "/home/z/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py", line 174, in tf_record_iterator
    compat.as_bytes(path), 0, compat.as_bytes(compression_type), status)
  File "/home/z/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/z/tensorflow_models_learning-master/dataset/record/train224.tfrecords; No such file or directory

博主，总是出现这个错误是怎么了？

**Comment by zeqingjiang** [comment]
> Traceback (most recent call last):
> File "/home/z/tensorflow_models_learning-master/create_tf_record.py", line 303, in 
> train_nums=get_example_nums(train_record_output)
> File "/home/z/tensorflow_models_learning-master/create_tf_record.py", line 39, in get_example_nums
> for record in tf.python_io.tf_record_iterator(tf_records_filenames):
> File "/home/z/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/tf_record.py", line 174, in tf_record_iterator
> compat.as_bytes(path), 0, compat.as_bytes(compression_type), status)
> File "/home/z/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: /home/z/tensorflow_models_learning-master/dataset/record/train224.tfrecords; No such file or directory
> 
> 博主，总是出现这个错误是怎么了？

这个很简单，直接在dataset目录下，新建一个record的文件夹就行
